<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * CartItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCartTotalPrice($id){
        return $this->createQueryBuilder('CartItem')
                        ->andWhere('CartItem.cartId = :id')
                        ->setParameter('id', $id)
                        ->select('SUM(CartItem.totalPrice) as totalPrice')
                        ->getQuery()
                        ->getSingleScalarResult();
                        
    }

    public function getUserCart($id){
        return $this->createQueryBuilder('ci')
                        ->andWhere('ci.cartId = :id')
                        ->select('p.name', 'ci.id', 'ci.quantity', 'ci.totalPrice')
                        ->innerJoin('ci.productId', 'p', 'WITH', 'ci.productId = p.id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->execute();
    }

    public function getItemIdArray($id){
        return $this->createQueryBuilder('ci')
                        ->andWhere('ci.cartId = :id')
                        ->select('ci.id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->getResult();
    }
}
