<?php

namespace AppBundle\Repository;

/**
 * CartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCartId($id){
        return $this->createQueryBuilder('Cart')
                        ->where("Cart.user_id = :id")
                        ->setParameter('id', $id)
                        ->select('Cart.id')
                        ->getQuery()
                        ->execute();
    }
    public function getUserCartCount($id){
        return $this->createQueryBuilder('c')
                        ->andWhere('c.userId = :id')
                        ->setParameter('id', $id)
                        ->select('COUNT(c.userId) as userCart')
                        ->getQuery()
                        ->getSingleScalarResult();
    }
}
