<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoryProduct($id){
        return $this->createQueryBuilder('cat')
                        ->where('cat.id = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->execute();
    }
}
