<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\Entity\Category;

class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductPrice($id){
        return $this->createQueryBuilder('Product')
                        ->where('Product.id = :id')
                        ->setParameter('id', $id)
                        ->select('Product.price')
                        ->getQuery()
                        ->execute();
    }

    public function getProductStock($id){
        return $this->createQueryBuilder('Product')
                        ->where('Product.id = :id')
                        ->setParameter('id', $id)
                        ->select('Product.stock')
                        ->getQuery()
                        ->execute();
    }

    // public function getProductWithCategory(){
    //     return $this->createQueryBuilder('Product, p')
    //                     ->innerJoin();
    // }

}
