<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
use AppBundle\Entity\Category;

class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductPrice($id){
        return $this->createQueryBuilder('Product')
                        ->where('Product.id = :id')
                        ->setParameter('id', $id)
                        ->select('Product.price')
                        ->getQuery()
                        ->execute();
    }

    public function getProductStock($id){
        return $this->createQueryBuilder('Product')
                        ->where('Product.id = :id')
                        ->setParameter('id', $id)
                        ->select('Product.stock')
                        ->getQuery()
                        ->execute();
    }

    public function getProductWithCategory(){
        return $this->createQueryBuilder('p')
                        ->select('p.id', 'p.name', 'cat.category AS category', 'p.availableQty', 'p.price')
                        ->innerJoin('p.categoryId', 'cat', 'WITH', 'p.categoryId = cat.id')
                        ->getQuery()
                        ->execute();
    }

    public function getCategoryProduct($id){
        return $this->createQueryBuilder('p')
                        ->where('p.categoryId = :id')
                        ->setParameter('id', $id)
                        ->getQuery()
                        ->execute();
    }

}
