<?php

namespace AppBundle\Repository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    public function getProductPrice($id){
        return $this->createQueryBuilder('Product, p')
                        ->where('p.id = :id')
                        ->setParameter('id', $id)
                        ->select('p.price')
                        ->getQuery()
                        ->execute();
    }

    public function getProductStock($id){
        return $this->createQueryBuilder('Product, p')
                        ->where('p.id = :id')
                        ->setParameter('id', $id)
                        ->select('p.stock')
                        ->getQuery()
                        ->execute();
    }
}
