<?php

namespace AppBundle\Repository;

/**
 * UserOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserOrderRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLatestUserOrder($userId){
        return $this->createQueryBuilder('uor')
                        ->where('uor.userId = :userId')
                        ->setParameter('userId', $userId)
                        ->orderBy('uor.createdAt', 'DESC')
                        ->setMaxResults(1)
                        ->getQuery()
                        ->getSingleResult();
    }
}
